# Generated by Django 4.0.1 on 2022-02-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0002_user_allegy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allegy',
            new_name='allergy',
        ),
    ]
